site_name: Driverless Kart Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Hardware:
      - Battery: hardware/battery/index.md
      - Camera: hardware/camera/index.md
      - Computer: hardware/computer/index.md
      - Motor: hardware/motor/index.md
      - Steering Angle Sensor: hardware/steering_angle_sensor/index.md
      - Emergency Braking System: hardware/ebs/index.md
  - Electronics:
      - Wiring: electronics/wiring.md
  - Software: software/index.md
  - FAQ: faq.md
  - Contact: contact.md
repo_url: https://github.com/UM-Driverless/kart-docs
edit_uri: edit/main/docs/
