site_name: Formula Student KART
theme:
  name: material
nav:
  - Home: index.md
  - Electronics:
      - Wiring: electronics/wiring.md
      - Battery: electronics/battery/index.md
  - Powertrain: powertrain/index.md
  - EBS: ebs/index.md
  - Contact: contact.md
repo_url: https://github.com/rubenayla/kart-docs
edit_uri: edit/main/docs/
